### ISSUE TITLE
[v0.9.3] Missing Bronze Ingot item in REI

### ISSUE THREAD

**Issue by LieSain1** [DenisMasterHerobrine/ElerionBloodNSteel#1]
Отсутствует в REI как таковой бронзовый слиток который идет по квестам, из мода Modern Industrial.... .
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/118547420/72fd4eb6-08c1-422f-ae72-a38acbd770f3)
Я так понял есть аналог из мода "Tech Reborn" но пролистав каждую страницу в REI я не нашел способа получения его на данном этапе. 

![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/118547420/36c71a94-d3b7-4f0a-b61c-ffe12bac6bd7)
Банальный крафт рода подразумевает за собой двойной слиток бронзы но одиночного нет. Есть только из "Tech Reborn".

**Comment by LieSain1** [comment]
В общем кто сталкнется с такой проблемой и не хочет ждать патча, то вам нужно
жмать сюда
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/118547420/606afc70-9503-4029-b6c9-55806286c17b)
потом сюда
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/118547420/ded55005-e847-4da0-ae8b-3bd731a1f09e)
затем туда
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/118547420/f06f6e54-3801-43c9-9620-cf5cca97118a)
после
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/118547420/2cf9d62d-bf1d-4145-94b7-e54e32d7a628)
еще раз
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/118547420/b9c011b7-505b-4ba0-a931-29326388b5df)
и вписать туда "@modern bronze ingot"
И ОБЯЗАТЕЛЬНО должно быть прожато "Показать"
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/118547420/d311b5f2-7bc9-4494-9540-98cf8ef23008)
затем готово, готово и обязательно сохраните. Может крашнуть, у меня крашнуло. И при заходе в мир все будет гуд. Играем дальше!

**Comment by TheFogIOF** [comment]
Фикс Бага
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/70043840/22a93bca-30a8-4841-9235-23710cad3ff5)
Переходите по этому пути и открываете файл unify.json

![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/70043840/d775b424-facc-4936-8f8b-23b0c0ab983f)
И в файле переместите "modern_industrialization" над "techreborn"
