### ISSUE TITLE
Баг с обычным камне резчиком

### ISSUE THREAD

**Issue by Smusken** [DenisMasterHerobrine/ElerionBloodNSteel#101]
Если положить предмет в камне резку для переделывания в другой блок, то после того как последний блок вытащить или переделать игра крашит. Если у тебя последний блок лежит в камне резке для переделки и нажать ESC, то игра не вылетит.

**Comment by Strelok797** [comment]
Аналогично, 
[crash-2024-07-20_16.52.27-client.txt](https://github.com/user-attachments/files/16321780/crash-2024-07-20_16.52.27-client.txt)
