### ISSUE TITLE
Не могу взаимодействовать с миром при заходе на сервер (в одиночном мире все работает)

### ISSUE THREAD

**Issue by Qwirik** [DenisMasterHerobrine/ElerionBloodNSteel#103]
При заходе на сервер нет возможности взаимодействовать с миром(ставить, ломать блоки, и нельзя есть, и открывать сундуки бочки и т.д.)
Ошибка возникает на собственном компьютере при запуске через powershell и на хостинге при запуске через bash.
https://youtu.be/9iCeS07R49g

**Comment by chelovek3093** [comment]
Подобное происходить видимо из-за прогрузки территории вокруг игрока, стоит отойти на пару чанков от места захода(или телепортации), как всё фиксится. У меня по крайней мере так было
