### ISSUE TITLE
0 FPS

### ISSUE THREAD

**Issue by michailVs** [DenisMasterHerobrine/ElerionBloodNSteel#104]
CPU: i7-4790 3.6GHz 4 cores 8 threads
GPU: AMD Radeon RX580 Pulse 8Gb
ОЗУ: 16 Gb DDR4 3200
Чтобы не делал fps не поднимался (краткосрочно) выше 10.

**Comment by DenisMasterHerobrine** [comment]
К сожалению, я ничего не могу сказать и ничем помочь без логов/сейва не могу. У меня нет миллиона компов с разными сетапами, чтобы знать, в чём может быть потенциальная причина. Велика вероятность, что AMD шалит со своими дровами или сборка работает на графическом процессоре именно процессора, а не AMD видеокарты.
