### ISSUE TITLE
Why are crafts more expensive in Forge Hammer?

### ISSUE THREAD

**Issue by N1zyx3** [DenisMasterHerobrine/ElerionBloodNSteel#105]
For example: a bronze plate can be crafted from 2 bronzes, when in the mod itself only 1 bronze is sufficient. Don't you think it's too expensive? For the same bronze evaporator in Chapter 1 you need to spend as much as 54-56 (I don’t remember exactly) bronze.

**Comment by bakardos** [comment]
It's idea of StaTech modpack on which Elerion's technical quests is based. This crafting ratio will force you to craft and use the compressor, cutter, etc as soon as possible.
Hint: you can craft plates with 1:1 ratio by mechanical press from Create.

**Comment by DenisMasterHerobrine** [comment]
This is an intended recipe, use Create to craft Bronze efficiently.
