### ISSUE TITLE
Полиэтилен из сахара и воды

### ISSUE THREAD

**Issue by navelyit** [DenisMasterHerobrine/ElerionBloodNSteel#108]
Не знаю бак ли это но нашёл крафт Полиэтилен из этилена который крафтится из этанола который крафтится из сахарного раствора
![2024-06-11_19-54-08](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/101657424/d655bf0e-40df-4a25-af52-695c9774e303)
![2024-06-11_19-49-55](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/101657424/2cebc668-7b55-44e8-b683-b4e080ba187a)
![2024-06-11_19-50-06](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/101657424/60fbb279-f722-4c0d-be0b-d31e52583b81)

**Comment by bakardos** [comment]
500mb этилена за 12 стаков сахара) Это крафт из StaTech и теоретически дизбалансным не является.

**Comment by DenisMasterHerobrine** [comment]
Это альтернативный крафт, который остался из-за того, что сборка является частичным форком StaTech Industry.
