### ISSUE TITLE
Сбой игры

### ISSUE THREAD

**Issue by JohnKarter94** [DenisMasterHerobrine/ElerionBloodNSteel#109]
Бегал по пещерам, выскочила ошибка сущности Скелет. Крашнуло игру и при повторной попытке запустить мир крашит на этапе загрузки территории. Как можно это исправить?
[crash-2024-06-13_00.18.10-server.txt](https://github.com/user-attachments/files/15808747/crash-2024-06-13_00.18.10-server.txt)

**Comment by DenisMasterHerobrine** [comment]
Предположу, что это из-за маленького скелета. В 0.9.5 был обновлён мод Neruina, который должен исправлять этот баг с Pehkui, который отвечает за атрибуты у поломанного Скелета в мире. Как вариант - включить мирный на мгновение, чтобы выгрузить моба, который крашит.

В большинстве случаев, отследить такую проблему крайне проблематично и почти нереально, шанс такого краша крайне мал, поэтому вряд ли это будет когда-либо решено.
