### ISSUE TITLE
Can't use hotbar

### ISSUE THREAD

**Issue by DeLoR1AnEc** [DenisMasterHerobrine/ElerionBloodNSteel#11]
Когда я пытаюсь поменять слот хотбара ничего не происходит. Взаимодействовать с миром могу, переставлять предметы в инвентаре тоже.

**Comment by R2kip** [comment]
Измени клавиши в настройках

**Comment by DeLoR1AnEc** [comment]
> Измени клавиши в настройках

Пытался но ничего не работало

**Comment by DenisMasterHerobrine** [comment]
Пробуй перезапускать игру или отжимать CTRL/ALT кнопки.

**Comment by DeLoR1AnEc** [comment]
Выяснил, оказывается просто лаг но очень специфичный - тормозящий только хотбар.
