### ISSUE TITLE
Отсутствует крафт

### ISSUE THREAD

**Issue by Flanch2005** [DenisMasterHerobrine/ElerionBloodNSteel#116]
Нету крафта расщепителя который присутствует в квестах перед креативными вешами

**Comment by mogibesf** [comment]
Насколько я помню сборка пока что не может быть пройдена до конца, только в следующих обновлениях.

**Comment by DenisMasterHerobrine** [comment]
Расщепитель имеет крафт, начиная с 0.9.5.
