### ISSUE TITLE
Вылезает ошибка при запуске 

### ISSUE THREAD

**Issue by Akula28** [DenisMasterHerobrine/ElerionBloodNSteel#117]
![Снимок экрана 2024-06-26 191535](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/173939921/df24c08a-7322-418c-8072-ea9059f911fb)

**Comment by mogibesf** [comment]
Выглядит так, как будто здесь несколько сборок перемешалось, не может быть такого ?

**Comment by DenisMasterHerobrine** [comment]
Попробуй переустановить сборку с чистого листа. Этих скриптов точно нет в сборке.
