### ISSUE TITLE
ошибка при запуске

### ISSUE THREAD

**Issue by bagrock** [DenisMasterHerobrine/ElerionBloodNSteel#118]
![Screenshot_14](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/174014650/4c409d56-b3fc-49ca-960c-81680ca10d7e)
![Screen_1](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/174014650/73dec125-4768-47c2-bc44-25e160ab186b)

**Comment by bagrock** [comment]
нет блять это я долбаеб

**Comment by Illuzia189** [comment]
а как это пофиксить?

**Comment by DenisMasterHerobrine** [comment]
Сборка на Fabric. Смею предположить, что ты пытался запустить сборку на Forge.
