### ISSUE TITLE
что делать блет

### ISSUE THREAD

**Issue by clowun230** [DenisMasterHerobrine/ElerionBloodNSteel#122]
хз чо делать 
![Скриншот 06-07-2024 233132](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/174906889/29cd14d6-e3c6-4764-ae64-9727267681f4)

**Comment by chelovek3093** [comment]
Не все моды установлены

**Comment by Nanachi104** [comment]
А ты на forge или fabric моды ставил?

**Comment by DenisMasterHerobrine** [comment]
Сборка на Fabric. Смею предположить, что ты пытался запустить сборку на Forge.
