### ISSUE TITLE
Краш при генерации/заходе в мир

### ISSUE THREAD

**Issue by nikitakakoito** [DenisMasterHerobrine/ElerionBloodNSteel#123]
сборку ставил через tl legacy, fabric качал с официального сайта, в краш логе версии такие, какие указаны в требованиях

[tl-logger5217141479907319330.txt](https://github.com/user-attachments/files/16118323/tl-logger5217141479907319330.txt)

а, и, ну, MacBook Air m2, если это важно хахаха

**Comment by kathlind** [comment]
для быстрой связи, если это будет необходимо: tg: @nikkinnik93

**Comment by kathlind** [comment]
upd: крашлог из под официального лаунчера


[hs_err_pid66623.log](https://github.com/user-attachments/files/16118737/hs_err_pid66623.log)

**Comment by DenisMasterHerobrine** [comment]
`~StubRoutines::SafeFetch32` - обнови джаву до версии 17.0.9+. Сборка совместима с Java 21 и 22. Или используй последнюю версию Java 8. Конкретно у тебя версия джавы крашит SafeFetch32, который в 17 джаве был неправильно инициализирован. (см. https://bugs.openjdk.org/browse/JDK-8283326)

- Сборка не работает с TLauncher/Legacy Launcher, используй другой лаунчер.
