### ISSUE TITLE
Баг про цвет ников там не ник а набор символов

### ISSUE THREAD

**Issue by MrTazik20** [DenisMasterHerobrine/ElerionBloodNSteel#138]
https://github.com/user-attachments/assets/09e32a65-eb63-4032-a81f-70cbfd0a1f0c
Когда выбрал роль нету цвета ников а выходит такая фигня фото есть

**Comment by N1zyx3** [comment]
В табе такая же история
![2024-08-11_18 30 48](https://github.com/user-attachments/assets/22f2837c-5800-4536-b46f-972915b36980)
