### ISSUE TITLE
проблема в входе

### ISSUE THREAD

**Issue by Mam1241** [DenisMasterHerobrine/ElerionBloodNSteel#139]
![Screenshot_51](https://github.com/user-attachments/assets/21ad17e9-ad25-425b-9201-02ae29b7e3d4)
хз что делать скажыте мне

**Comment by MrTazik20** [comment]
если не решил проблему тебе надо скачать мод tlskipcape 1.30  мне помогло эту проблему решить вот ссылка на мод

https://tlmods.org/en/mods/tl-skin-and-cape/?ysclid=lzpqgxvnk8389937136

**Comment by Mam1241** [comment]
> если не решил проблему тебе надо скачать мод tlskipcape 1.30  мне помогло эту проблему решить вот ссылка на мод
> 
> https://tlmods.org/en/mods/tl-skin-and-cape/?ysclid=lzpqgxvnk8389937136

Окей я попробую щас

**Comment by Mam1241** [comment]
> если не решил проблему тебе надо скачать мод tlskipcape 1.30 мне помогло эту проблему решить вот ссылка на мод
> 
> https://tlmods.org/en/mods/tl-skin-and-cape/?ysclid=lzpqgxvnk8389937136

нет не помогло печально хз тагже выходить эта ошыбка

**Comment by MrTazik20** [comment]
как я делал я удалил мод в сборке и потом вставил тот мод который я скачал если я просто ставил без удаления выходила такая же ошибка

ну или попробуй сборку переустановить
