### ISSUE TITLE
при заходе на сервер ко мне через radminvpn у друга вылетает ошибка

### ISSUE THREAD

**Issue by ZUBKACRA** [DenisMasterHerobrine/ElerionBloodNSteel#141]
![photo_2024-08-12_00-36-47](https://github.com/user-attachments/assets/bffb0dc7-6427-46d3-9527-af33a8fab193)

index 16777216 out o bounds for lenght 3

**Comment by Wapevths** [comment]
https://t.me/dmhdev/723 (ссылка на автора)

**Comment by DenisMasterHerobrine** [comment]
Исправлено в 0.9.5.1. Для версии 0.9.5 есть фикс в ТГ или на бусти.
