### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by Texno-cat** [DenisMasterHerobrine/ElerionBloodNSteel#142]
При запуске майна почему то не загружаться 12 модов, все ставил как писали, я не особо шарю, не знаю в чем может быть проблема.
![javaw_tstNNa5Xbu](https://github.com/user-attachments/assets/7874fbea-e1b4-4ad7-92e9-bbabf3daf101)

**Comment by DenisMasterHerobrine** [comment]
Предполагаю, что ты запускаешься через Forge. Сборка на Fabric.
