### ISSUE TITLE
Miskatonic-Mysteries crash with Profane Chalk

### ISSUE THREAD

**Issue by Beta-Blaze** [DenisMasterHerobrine/ElerionBloodNSteel#143]
При использовании любого Profane Chalk из мода Miskatonic-Mysteries образуется невидимое забаганное энтити, при взаимодействии с ним neruina кикает с сервера (зайти обратно не получится, пока игрока не тепнет с энтити), если запретить neruina кикать игроков, то взамен кика произойдёт краш игры. Также это энтити не удаляется командами.

**Comment by DenisMasterHerobrine** [comment]
Исправлено в 0.9.5.1. Мод обновлён до версии 0.1.10.
(https://github.com/BehindTheScenery/Miskatonic-Mysteries-Fabric/commit/0191afcffde3a7088d1be8f0669ea912f5954918)
