### ISSUE TITLE
При попытки выбрать произхождение godness пишет ошибку 

### ISSUE THREAD

**Issue by Themediocrity** [DenisMasterHerobrine/ElerionBloodNSteel#144]
Я выбрал техника но не мог поднимать предметы из MI, я попытался поставить произхождение goddess но мне написало что это произхождения не зарегистрировано в layer origins:origin
![image](https://github.com/user-attachments/assets/22c93b80-07ed-4875-ac60-91dd387a32ff)

**Comment by Supchk** [comment]
Нужно добавить строку в файле: (папка cj сборкой\сервом)\global_packs\required_data\ 
Там архив, распаковываешь его и идешь дальше по пути, как добавишь нужную строку - заархивируешь как было.
origins_elerion_roles.zip/data/origins/origin_layers/origin.json

{
  "replace": false,
  "origins": [
    "elerion_blood_and_steel:technician",
    "elerion_blood_and_steel:magician",
	"elerion_blood_and_steel:goddess"
  ]
}

Попробуй так сделать, мне помогло

**Comment by aimzi16** [comment]
> Нужно добавить текст в файл: (папка cj сборкой\сервом)\global_packs\required_data\ Там архив, распаковываешь его и идешь дальше по пути, как добавишь нужный формат — заархивируешь, как было. origins_elerion_roles.zip/data/origins/origin_layers/origin.json
> 
> { "replace": false, "origins": [ "elerion_blood_and_steel:technician", "elerion_blood_and_steel:magician", "elerion_blood_and_steel:goddess" ] }
> 
> Попробуй так сделать, мне помогло

сделал все точно также, в игре выставил goddess и теперь не могу брать ни магические, ни технические предметы

**Comment by Vildak2004** [comment]
> Нужно добавить строку в файле: (папка cj сборкой\сервом)\global_packs\required_data\ Там архив, распаковываешь его и идешь дальше по пути, как добавишь нужную строку - заархивируешь как было. origins_elerion_roles.zip/data/origins/origin_layers/origin.json
> 
> { "replace": false, "origins": [ "elerion_blood_and_steel:technician", "elerion_blood_and_steel:magician", "elerion_blood_and_steel:goddess" ] }
> 
> Попробуй так сделать, мне помогло

Попробовал, роль goddess появилась и я смог поднимать предметы техников и магов, но после перезахода не смог поднимать предметы техников и магов
