### ISSUE TITLE
Не могу зайти в майнкрафт при запуске фабрика

### ISSUE THREAD

**Issue by UFugaU** [DenisMasterHerobrine/ElerionBloodNSteel#146]
Вылетает ошибка просто из за кого-то одного мода не знаю как фиксить пробовал всё 
![mine](https://github.com/user-attachments/assets/a1f53a75-b384-4972-a410-abcbedfc0fb8)

**Comment by mogibesf** [comment]
Либо покупай майнкрафт, либо меняй лаунчер. Тлаунчер скачивает свой мод в папку с игрой, из-за этого моды не могут правильно работать.

**Comment by chelovek3093** [comment]
Просто убери в настройках сборки галочку "Использовать систему скинов Tlauncher"

**Comment by DenisMasterHerobrine** [comment]
Конфликт с модом TL Skin Capes. Удали этот мод.
Сборка не поддерживает TLauncher/Legacy Launcher. Используй другой лаунчер.
