### ISSUE TITLE
Привет Денис кароче этот баг уже давно но не приятный 

### ISSUE THREAD

**Issue by MrTazik20** [DenisMasterHerobrine/ElerionBloodNSteel#154]
Короче дебильная мэ система потребляет в 10-12 раз больше энергии чем должна и это меня бесит я не могу делать нормальные авто крафты

это без ускорителя роста кристаллов
https://github.com/user-attachments/assets/8db2e81d-c76e-42d9-a105-5652f8e1ee1b

https://github.com/user-attachments/assets/e738f86f-24f4-4959-9452-f0267ac0b6a2
а это уже с ним 1 ука

**Comment by DenisMasterHerobrine** [comment]
Так и задумано, это не баг, МЕ раньше действительно много ела, аж 400-600 E/t за такой сетап, она была пробаффана до 100 E/t за такой сетап. Считаю балансным данный расход энергии. Используй бойлеры/турбины/разные способы генерировать энергию.
