### ISSUE TITLE
Nano armor

### ISSUE THREAD

**Issue by Grogodems** [DenisMasterHerobrine/ElerionBloodNSteel#16]
Нано броня не тратит энергию при получения урона и проходит обыный урон персонажу, так же ей нельзя рерольнуть на наковальне

**Comment by DenisMasterHerobrine** [comment]
Dynamic Difficulty mod issue, no config provided for Fabric version?

**Comment by Grogodems** [comment]
https://www.curseforge.com/minecraft/mc-mods/tech-enhanced/comments

**Comment by Grogodems** [comment]
https://github.com/Thepigcat76/Tech-enhanced
