### ISSUE TITLE
There were KubeJS startup errors

### ISSUE THREAD

**Issue by ArliumZam** [DenisMasterHerobrine/ElerionBloodNSteel#18]
Error loading KubeJS script startup_scripts:launch.js': Line 3 'OnEvent()' is no longer supported

Error loading KubeJS script startup_scripts:trading.js': Line 25 'OnEvent()' is no longer supported
![Uploading 2024-04-26_08-39-29.png…]()

**Comment by DenisMasterHerobrine** [comment]
Недостаточно информации. Возможно неправильно установлена сборка. Таких линий вообще нет в сборке.
