### ISSUE TITLE
Drill from @Modern Industrialisation

### ISSUE THREAD

**Issue by SantosODonnell** [DenisMasterHerobrine/ElerionBloodNSteel#23]
Не отображаются рецепты в карьере у дрелей

**Comment by LieSain1** [comment]
Можешь отключить филтрацию в REI (Временное решение)
https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/issues/8

**Comment by DenisMasterHerobrine** [comment]
Duplicate of https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/issues/8
