### ISSUE TITLE
Create: Copycats+ вместо carpenters мода

### ISSUE THREAD

**Issue by DeLoR1AnEc** [DenisMasterHerobrine/ElerionBloodNSteel#31]
На версию 1.19.2 есть мод Create: Copycats+ который добавляет разные карпентерс блоки и работает стабильно
https://modrinth.com/mod/copycats

**Comment by DenisMasterHerobrine** [comment]
Будет поставлен отдельный форк мода Templates вместо Copycats+, хотя у мода есть свой вайб.
