### ISSUE TITLE
Crash (Spectrum mod - Bedrock dimension - Eraser mob)

### ISSUE THREAD

**Issue by Gwinbleidddd** [DenisMasterHerobrine/ElerionBloodNSteel#34]
Зашел в портал в измерение Spectrum под бедроком, через некоторое время начался пролаг, Neruina удалила несколько тикающих мобов, но это не помогло, случился краш и теперь краш происходит каждый раз при заходе в мир.
Во всех краш репортах виновник - моб spectrum:eraser.
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/97760191/14a56712-c9ae-4cf3-b0de-dd9cf0f6165e)
[crash-2024-04-29_20.32.23-server.txt](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15152802/crash-2024-04-29_20.32.23-server.txt)

**Comment by LieSain1** [comment]
Похожая проблема но только вообще со всеми энтити. По миру разбросаны подобные данжи
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/118547420/43a53b75-20e9-4288-83c8-1d33b902a2f7)
И почему то когда заходишь в них Neruina тупо спамит в чат и тебя крашит, и если ты на сервере то все крашится.

Вот пару краш логов.
[crash-2024-04-29_20.26.36-server.txt](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15153248/crash-2024-04-29_20.26.36-server.txt)
[crash-2024-04-29_20.24.48-server.txt](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15153249/crash-2024-04-29_20.24.48-server.txt)
[crash-2024-04-29_20.23.00-server.txt](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15153253/crash-2024-04-29_20.23.00-server.txt)
[crash-2024-04-29_20.20.04-server.txt](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15153256/crash-2024-04-29_20.20.04-server.txt)
[crash-2024-04-29_20.00.02-server.txt](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15153258/crash-2024-04-29_20.00.02-server.txt)
[crash-2024-04-29_19.57.28-server.txt](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15153259/crash-2024-04-29_19.57.28-server.txt)

В каждой ситуации абсолютно разные ентити вызвавшие краш.

Причем это все очень странно происходит, как буд то данж/здание как тригер к какому то событию. Событию краша)


Так же думаю стоит сказать что мы играем на сборке накинутой на сервер.
Почему то игрок который зашел в эти строения, начал вызывать краши, и собственно когда он заходил в игру сервер снова крашился, сперва по причине того что он находился в тригере строения, потом вовсе из-за того что он просто заходил на сервер не зависимо от расположения. Меня по прежнему вместе с сервером крашило когда я подлетал к строению. Много что перепробовали, но помогло только отчистить дату игрока из папки world.

Паранормальные явления, к которым даже цепочку зависимостей от чего все это происходит сложно подобрать. В причинах краша от ентити, у нас даже встречалась овца с именем jeb_
 
Я как смог описал все происходящее, надеюсь хоть что то будет понятно.

**Comment by DenisMasterHerobrine** [comment]
Fix: update Useless Reptile to 0.7.1 https://modrinth.com/mod/useless-reptile/version/0.7.1-1.19.2

Mod incompatibility with Biome Makeover and Useless Reptile.
Related to https://github.com/NordAct/useless-reptile/commit/c25b8928a19953404e8379f0ddf2d53c1f9381f6
