### ISSUE TITLE
Fix Ducky Peripherals Entity Detector limits

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [DenisMasterHerobrine/ElerionBloodNSteel#35]

**Comment by ftoh** [comment]
Hardcoded https://github.com/SamsTheNerd/ducky-periphs/blob/185319a255c460c888420313f687a15096720f7e/common/src/main/java/com/samsthenerd/duckyperiphs/peripherals/EntityDetector/EntityDetectorPeripheral.java#L18C23-L18C36
