### ISSUE TITLE
[v0.9.3] A typo in the translation.

### ISSUE THREAD

**Issue by agnotrodna** [DenisMasterHerobrine/ElerionBloodNSteel#4]
Не сильно страшный баг, однако в переводе некоторых уведомлений есть опечатки (Удалось запечатлеть только одну). предлагаю не закрывать данный Issues, чтобы здесь аккумулировались все опечатки в переводе, дабы потом одним апдейтом их все сразу решить, а не лазить ради 1 буквы каждый день.

![2024-04-22_20-30-15](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/65828409/28bd17df-ff82-4696-b2c9-1a9238f5cd27)

**Comment by DenisMasterHerobrine** [comment]
В сборке перевод не предусмотрен, опечатка в самом моде.
