### ISSUE TITLE
Fly on gravity chestplate and quantum chestplates

### ISSUE THREAD

**Issue by Grogodems** [DenisMasterHerobrine/ElerionBloodNSteel#49]
Полёт на гравитационном нагруднике и квантовый нагрудниках чуток сломан. В начале всё нормально, но потом он отключается . Если держать пробел, то после отключения, персонаж останется висеть на месте, а если при зажатом пробел пойти дальше, то он будет прыгать по воздуху на 1 блок выше.

**Comment by DenisMasterHerobrine** [comment]
Use Jet Suit instead of GraviChestPlate, Ad Astra will replace the GCP in 0.9.5+
