### ISSUE TITLE
Add New mod Create : Armory 

### ISSUE THREAD

**Issue by Grogodems** [DenisMasterHerobrine/ElerionBloodNSteel#51]
Может добавить этот мод? Create : Armory

**Comment by Grogodems** [comment]
https://www.curseforge.com/minecraft/mc-mods/create-armory

**Comment by R2kip** [comment]
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/56793105/7f5416f9-ccf1-4d9c-8f10-fd01909293a2)
Нет, версии на fabric
