### ISSUE TITLE
Добавь  если возможно Create: Armor and Weapons Addon 

### ISSUE THREAD

**Issue by Grogodems** [DenisMasterHerobrine/ElerionBloodNSteel#52]
https://www.curseforge.com/minecraft/mc-mods/create-tools-and-weapons-addon

**Comment by R2kip** [comment]
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/56793105/5d6af00d-faea-48f8-ab99-b23bead21a18)
Где ты тут нашёл 1.19.2 fabric?
