### ISSUE TITLE
Mobs with the Protected effect (immortal)

### ISSUE THREAD

**Issue by R2kip** [DenisMasterHerobrine/ElerionBloodNSteel#53]

**Comment by R2kip** [comment]
Фикс: Замените в файле ./config/randommobeffects/blacklist.txt

`minecells:protected` > `!minecells:protected`

Желательно ещё (Этот эффект спавнит мутантов которые хорошо нагружают сервер):
`mutantmonsters:chemical_x` > `!mutantmonsters:chemical_x`

**Comment by DenisMasterHerobrine** [comment]
already fixed in dev
