### ISSUE TITLE
Some portals dimensional doors spawns endermans

### ISSUE THREAD

**Issue by Grogodems** [DenisMasterHerobrine/ElerionBloodNSteel#57]
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/121344231/1c0c8a39-952a-45f8-966d-a4d563f167d6)
Некоторые порталы dimensional doors спавнят бесконечное количество эндерменов, которые не диспавнятся со временем

**Comment by Lakki4545** [comment]
Это механика мода
