### ISSUE TITLE
[v0.9.3] Assembly update

### ISSUE THREAD

**Issue by MartinDawgor** [DenisMasterHerobrine/ElerionBloodNSteel#6]
В сборке присутствуют устаревшие версии модов, прикрепляю список этих модов и отдельно скачанные новые версии.
Чисто эстетическое обновление для стабильности, сборка запустилась после обновления:
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/167915347/e4cc0d04-5b9c-4692-9b6d-1f6371fa293e)
Ну и ссылку сразу на все новые моды:
[GoogleDrive](https://drive.google.com/file/d/1xGmu7RxkXE8kmwsNBXXY_ivAntp0B1m_/view?usp=sharing)

**Comment by LieSain1** [comment]
Там если не замечал, некоторые моды помечены как про патченные

**Comment by DenisMasterHerobrine** [comment]
Проблема в том, что как раз обновления мне далеко не всех модов нужны. Я пообновляю большую часть из них в ближайшем крупном апдейте, но пока что нам хватает нюансов и неточностей сейчас не только от обновлений. Пока ишью закрою. Про обновления будет отдельный разговор.
