### ISSUE TITLE
краш вместо лимбо

### ISSUE THREAD

**Issue by MrGememoder** [DenisMasterHerobrine/ElerionBloodNSteel#60]
пошёл в портал и здох но вместо того чтобы попасть в лимбо я попал в вечное сохранение мира и в итоге после закрытия майна были ошибки рендеринга (вот логи https://paste.ee/p/TPyNV)

**Comment by R2kip** [comment]
Скинь crash log

**Comment by MrGememoder** [comment]
Сылка это и есть логи

**Comment by Lakki4545** [comment]
Кинь логи из crash-report

**Comment by MrGememoder** [comment]
[2024-05-03-2.log](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15223029/2024-05-03-2.log)
