### ISSUE TITLE
нет возможности передвигая при заходе на сервер а также зависание  в  воздухе

### ISSUE THREAD

**Issue by Nold0r** [DenisMasterHerobrine/ElerionBloodNSteel#61]
при заходе на сервер я не могу двигается и замираю в воздухе при этом это видят все игра не залагиавает я могу ломать блоки получать урон  и другие возможности единственное что я  не  могу это ходить и стою в воздухе

**Comment by R2kip** [comment]
На сервере похоже нет Valkyrien Skies 2. 
Удалите Valkyrien Skies 2

**Comment by Mirakll** [comment]
каво удалите это один из прикольнейших модов

**Comment by R2kip** [comment]
> каво удалите это один из прикольнейших модов

Ну у выбирай или не играть или играть без мода

Если спросите у владельца сервера есть этот мод на сервере:
Если нет мода > Удалите мод 
Иначе отпишите сюда

**Comment by Kolya-YT** [comment]
> при заходе на сервер я не могу двигается и замираю в воздухе при этом это видят все игра не залагиавает я могу ломать блоки получать урон и другие возможности единственное что я не могу это ходить и стою в воздухе

Установи на сервер эту версию мода и будет всё работать. [Valkyrien Skies 2](https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies/files/4654273)

**Comment by Lakki4545** [comment]
Если проблема ещё осталась, то лучше проверить схожесть модов на сервере и клиенте, возможно в этом и дело, было такое когда на моем сервере я не мог двигаться, в итоге оказалось что на клиенте были моды которых нет на сервере
