### ISSUE TITLE
- мир из за чешуйниц

### ISSUE THREAD

**Issue by MrGememoder** [DenisMasterHerobrine/ElerionBloodNSteel#63]
[Архив ZIP - WinRAR.zip](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15225113/ZIP.-.WinRAR.zip)
реплей
[2024-05-06-3.log.gz](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15225125/2024-05-06-3.log.gz)
логи
всё из за 406 чешуйниц

**Comment by R2kip** [comment]
А откуда 400 чешуйниц?

**Comment by MrGememoder** [comment]
Перамида в джунглях путину сделала чешуйница

**Comment by MrGememoder** [comment]
Могу скинуть корды и сид мира

**Comment by Lakki4545** [comment]
Путину?

**Comment by MrGememoder** [comment]
Паутину
