### ISSUE TITLE
Баг спектрума

### ISSUE THREAD

**Issue by Gawrick** [DenisMasterHerobrine/ElerionBloodNSteel#66]
При изучении столкнулся с проблемой, в какой-то момент потребуется найти "русалочий гребешок", это растение, которое растёт на дне океана и при созревании выплёвывает плод, который всплывает на поверхность, по крайней мере должен всплывать. В куче гайдов и обзоров на мод, да и в целом я так понимаю в чистом моде так задумано, что он всплывает. В данной сборке же обнаружена проблема, что при созревании плод тонет, что делает его поиски намного сложнее

**Comment by DenisMasterHerobrine** [comment]
Added an additional recipe for the Mermaid's Gem
