### ISSUE TITLE
KubeJS startup error

### ISSUE THREAD

**Issue by Gero0308** [DenisMasterHerobrine/ElerionBloodNSteel#68]
Игра запускается, но просто выводит вот такую ошибку (скрин закреплён)
![Снимок экрана 2024-05-10 220050](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/169490677/6db100a2-94ec-49d1-a734-0e0f85a4d155)
Что с этим делать (Играю с Klauncher-а)

**Comment by GravCom** [comment]
попробуй найти расположение файла startup_scripts и заменить пятую линию в файле script.js на это `StartupEvents.registry('item', event => {`, у меня сработало
скрины как было и что должно быть
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/169554568/f8d3fc6f-d014-4175-9269-94e77fa7c9e4)
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/169554568/1417ec5c-176a-4717-a829-d6de63700f52)

**Comment by Gero0308** [comment]
Не нашёл startup_script.js, перелазил все папки, не подскажешь где нашёл этот файл?

**Comment by DenisMasterHerobrine** [comment]
Это дефолтный тестовый файл, скорее всего неправильно установил сборку и не закинул чистую папку kubejs из архива.

**Comment by GravCom** [comment]
> Не нашёл startup_script.js, перелазил все папки, не подскажешь где нашёл этот файл?

\AppData\Roaming\.minecraft\kubejs\startup_scripts, там будет файл script.js, в нём изменить пятую строчку
