### ISSUE TITLE
Есть ли способ запустить сборку на сервере

### ISSUE THREAD

**Issue by EndrickN** [DenisMasterHerobrine/ElerionBloodNSteel#69]
Как можно запустить сборку на сервере очень надо

**Comment by Kolya-YT** [comment]
Не поверишь, руками.

**Comment by EndrickN** [comment]
И как это сделать?

**Comment by LieSain1** [comment]
Не поверишь! Руками.

**Comment by DenisMasterHerobrine** [comment]
На бусти уже есть серверный пак для тех, кому нужен сервер.
