### ISSUE TITLE
Ошибка запуска сервера 

### ISSUE THREAD

**Issue by NetrunnerAfter** [DenisMasterHerobrine/ElerionBloodNSteel#73]
При запуске сервера на хосте выдает ошибку и зависает запуск, на пк же все запускается

Заранее пишу что на хосте запускаю через .jar файл а не .sh 
так же используется java21
вот часть лога с самой ошибкой
`[19:11:05]` [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'advancedgenetics'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.10.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-launcher.jar:1.0.1]
	Suppressed: java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
		at com.electronwill.nightconfig.core.file.FileWatcher$WatchedDir.<init>(FileWatcher.java:220) ~[com_electronwill_night-config_core-3.6.6-3b735b3a536c03a7.jar:?]
		at com.electronwill.nightconfig.core.file.FileWatcher$WatchedDir.<init>(FileWatcher.java:210) ~[com_electronwill_night-config_core-3.6.6-3b735b3a536c03a7.jar:?]
		at com.electronwill.nightconfig.core.file.FileWatcher.lambda$addWatch$0(FileWatcher.java:81) ~[com_electronwill_night-config_core-3.6.6-3b735b3a536c03a7.jar:?]
		at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
		at com.electronwill.nightconfig.core.file.FileWatcher.addWatch(FileWatcher.java:81) ~[com_electronwill_night-config_core-`

**Comment by irunil-ru** [comment]
Что за хостинг?
Пробовал Java другой версии? К Примеру 17-18?

**Comment by NetrunnerAfter** [comment]
> Что за хостинг? Пробовал Java другой версии? К Примеру 17-18?

мой личный дедик с птерой для удобства
Джаву пробовал 17-21 нескольких версий и jre17-21 тоже нескольких версий

**Comment by irunil-ru** [comment]
Как я понял птера это тип расширение для питона?
Сама система какая?
И скинь лучше полный лог, чтобы было проще ориентироваться что да как, файлом или просто текстом
Также скинь как именно через у тебя запускается jar файл, мб там у тебя косяк есть

**Comment by NetrunnerAfter** [comment]
> Как я понял птера это тип расширение для питона? Сама система какая? И скинь лучше полный лог, чтобы было проще ориентироваться что да как, файлом или просто текстом Также скинь как именно через у тебя запускается jar файл, мб там у тебя косяк есть

птера это птеродактиль, панель для удобства управления сервером https://pterodactyl.io/
Строка запуска выглядит так 
java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar fabric-server-launcher.jar
а лог вот
[latest.log](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15318903/latest.log)

**Comment by irunil-ru** [comment]
Аааа, всё понял, забыл совсем о ней
Лог не тот, там у тебя в нём просто работа ICL
По строке запуска, лучше не использовать на моддовом сервере флаги `-XX:MaxRAMPercentage=` и `-XX:MinRAMPercentage=`, да и вообще в принципе их не использовать, попробуй лучше через `-Xmx8G`, ну или сколько там памяти ты хочешь выделить, под систему учитывая птеру лучше всего оставлять хотябы 2-3Гб

Попробуй запустить с `-Xmx` если опять будет тогда скинь краш-репорт

**Comment by NetrunnerAfter** [comment]
> Аааа, всё понял, забыл совсем о ней Лог не тот, там у тебя в нём просто работа ICL По строке запуска, лучше не использовать на моддовом сервере флаги `-XX:MaxRAMPercentage=` и `-XX:MinRAMPercentage=`, да и вообще в принципе их не использовать, попробуй лучше через `-Xmx8G`, ну или сколько там памяти ты хочешь выделить, под систему учитывая птеру лучше всего оставлять хотябы 2-3Гб
> 
> Попробуй запустить с `-Xmx` если опять будет тогда скинь краш-репорт

краш репорт не создается сервер не крашится а просто зависает насмерть и потребление процессора падает до 2-4\%

**Comment by NetrunnerAfter** [comment]
> Аааа, всё понял, забыл совсем о ней Лог не тот, там у тебя в нём просто работа ICL По строке запуска, лучше не использовать на моддовом сервере флаги `-XX:MaxRAMPercentage=` и `-XX:MinRAMPercentage=`, да и вообще в принципе их не использовать, попробуй лучше через `-Xmx8G`, ну или сколько там памяти ты хочешь выделить, под систему учитывая птеру лучше всего оставлять хотябы 2-3Гб
> 
> Попробуй запустить с `-Xmx` если опять будет тогда скинь краш-репорт

[latest (3).log](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15319574/latest.3.log)
Вот лог

**Comment by NetrunnerAfter** [comment]
> > Аааа, всё понял, забыл совсем о ней Лог не тот, там у тебя в нём просто работа ICL По строке запуска, лучше не использовать на моддовом сервере флаги `-XX:MaxRAMPercentage=` и `-XX:MinRAMPercentage=`, да и вообще в принципе их не использовать, попробуй лучше через `-Xmx8G`, ну или сколько там памяти ты хочешь выделить, под систему учитывая птеру лучше всего оставлять хотябы 2-3Гб
> > Попробуй запустить с `-Xmx` если опять будет тогда скинь краш-репорт
> 
> [latest (3).log](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15319574/latest.3.log) Вот лог

и если есть возможность связаться через дискорд для ускорения данного процесса 
DISCORD; __netrunner__

**Comment by irunil-ru** [comment]
> > > Аааа, всё понял, забыл совсем о ней Лог не тот, там у тебя в нём просто работа ICL По строке запуска, лучше не использовать на моддовом сервере флаги `-XX:MaxRAMPercentage=` и `-XX:MinRAMPercentage=`, да и вообще в принципе их не использовать, попробуй лучше через `-Xmx8G`, ну или сколько там памяти ты хочешь выделить, под систему учитывая птеру лучше всего оставлять хотябы 2-3Гб
> > > Попробуй запустить с `-Xmx` если опять будет тогда скинь краш-репорт
> > 
> > 
> > [latest (3).log](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15319574/latest.3.log) Вот лог
> 
> и если есть возможность связаться через дискорд для ускорения данного процесса DISCORD; **netrunner**

Отправил запрос дружбы в дс, там уже тогда более детально спишемся и решим проблему твою, но уже есть подозрение

**Comment by NetrunnerAfter** [comment]
> > > > Аааа, всё понял, забыл совсем о ней Лог не тот, там у тебя в нём просто работа ICL По строке запуска, лучше не использовать на моддовом сервере флаги `-XX:MaxRAMPercentage=` и `-XX:MinRAMPercentage=`, да и вообще в принципе их не использовать, попробуй лучше через `-Xmx8G`, ну или сколько там памяти ты хочешь выделить, под систему учитывая птеру лучше всего оставлять хотябы 2-3Гб
> > > > Попробуй запустить с `-Xmx` если опять будет тогда скинь краш-репорт
> > > 
> > > 
> > > [latest (3).log](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15319574/latest.3.log) Вот лог
> > 
> > 
> > и если есть возможность связаться через дискорд для ускорения данного процесса DISCORD; **netrunner**
> 
> Отправил запрос дружбы в дс, там уже тогда более детально спишемся и решим проблему твою, но уже есть подозрение

отправь свой дискорд пожалуйста , ибо в моем теге спереди и сзади два нижних подчеркивания но гитхаб решиб что это измена шрифта

**Comment by NetrunnerAfter** [comment]
> > > > Аааа, всё понял, забыл совсем о ней Лог не тот, там у тебя в нём просто работа ICL По строке запуска, лучше не использовать на моддовом сервере флаги `-XX:MaxRAMPercentage=` и `-XX:MinRAMPercentage=`, да и вообще в принципе их не использовать, попробуй лучше через `-Xmx8G`, ну или сколько там памяти ты хочешь выделить, под систему учитывая птеру лучше всего оставлять хотябы 2-3Гб
> > > > Попробуй запустить с `-Xmx` если опять будет тогда скинь краш-репорт
> > > 
> > > 
> > > [latest (3).log](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15319574/latest.3.log) Вот лог
> > 
> > 
> > и если есть возможность связаться через дискорд для ускорения данного процесса DISCORD; **netrunner**
> 
> Отправил запрос дружбы в дс, там уже тогда более детально спишемся и решим проблему твою, но уже есть подозрение

отправь свой дискорд пожалуйста , ибо в моем теге спереди и сзади два нижних подчеркивания но гитхаб решиб что это измена шрифта

**Comment by irunil-ru** [comment]
> > > > > Аааа, всё понял, забыл совсем о ней Лог не тот, там у тебя в нём просто работа ICL По строке запуска, лучше не использовать на моддовом сервере флаги `-XX:MaxRAMPercentage=` и `-XX:MinRAMPercentage=`, да и вообще в принципе их не использовать, попробуй лучше через `-Xmx8G`, ну или сколько там памяти ты хочешь выделить, под систему учитывая птеру лучше всего оставлять хотябы 2-3Гб
> > > > > Попробуй запустить с `-Xmx` если опять будет тогда скинь краш-репорт
> > > > 
> > > > 
> > > > [latest (3).log](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15319574/latest.3.log) Вот лог
> > > 
> > > 
> > > и если есть возможность связаться через дискорд для ускорения данного процесса DISCORD; **netrunner**
> > 
> > 
> > Отправил запрос дружбы в дс, там уже тогда более детально спишемся и решим проблему твою, но уже есть подозрение
> 
> отправь свой дискорд пожалуйста , ибо в моем теге спереди и сзади два нижних подчеркивания но гитхаб решиб что это измена шрифта

irunil

**Comment by NetrunnerAfter** [comment]
> > > > > > Аааа, всё понял, забыл совсем о ней Лог не тот, там у тебя в нём просто работа ICL По строке запуска, лучше не использовать на моддовом сервере флаги `-XX:MaxRAMPercentage=` и `-XX:MinRAMPercentage=`, да и вообще в принципе их не использовать, попробуй лучше через `-Xmx8G`, ну или сколько там памяти ты хочешь выделить, под систему учитывая птеру лучше всего оставлять хотябы 2-3Гб
> > > > > > Попробуй запустить с `-Xmx` если опять будет тогда скинь краш-репорт
> > > > > 
> > > > > 
> > > > > [latest (3).log](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15319574/latest.3.log) Вот лог
> > > > 
> > > > 
> > > > и если есть возможность связаться через дискорд для ускорения данного процесса DISCORD; **netrunner**
> > > 
> > > 
> > > Отправил запрос дружбы в дс, там уже тогда более детально спишемся и решим проблему твою, но уже есть подозрение
> > 
> > 
> > отправь свой дискорд пожалуйста , ибо в моем теге спереди и сзади два нижних подчеркивания но гитхаб решиб что это измена шрифта
> 
> irunil

отправил
