### ISSUE TITLE
Опечатка в названии

### ISSUE THREAD

**Issue by DjonLibin** [DenisMasterHerobrine/ElerionBloodNSteel#76]
Когда я получил прокачку лопаты с 1 на 2 уровень я заметил опечатку в названии класса : "Лопаиа"
![Desktop Screenshot 2024 05 15 - 18 04 58   53](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/169909944/5f2c99a4-1245-4d2f-be3c-167bed594faa)

**Comment by DenisMasterHerobrine** [comment]
Duplicate of https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/issues/4
