### ISSUE TITLE
Rename "болт" (rod) to "стержень" to avoid repetition

### ISSUE THREAD

**Issue by kito-s** [DenisMasterHerobrine/ElerionBloodNSteel#79]
The bronze ones are just for example
---
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/169927425/0856805a-94ba-4d8b-845d-458d9b494f46)
![image](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/169927425/4ce0408b-f243-472f-8a23-a566251463d0)

**Comment by DenisMasterHerobrine** [comment]
Проблема локализации самого мода. Перевода официального в сборке нету.
