### ISSUE TITLE
Как называется мод на магию 

### ISSUE THREAD

**Issue by EndrickN** [DenisMasterHerobrine/ElerionBloodNSteel#81]
Как называется мод на магию где надо рисовать заклинания?

**Comment by MartinDawgor** [comment]
hex

**Comment by EndrickN** [comment]
А он есть на 1.20.1

**Comment by EndrickN** [comment]
А он есть на 1.20.1

**Comment by DenisMasterHerobrine** [comment]
https://www.curseforge.com/minecraft/mc-mods/hexcasting
