### ISSUE TITLE
Ошибка kubejs при запуске сервера

### ISSUE THREAD

**Issue by chelovek3093** [DenisMasterHerobrine/ElerionBloodNSteel#82]
При попытке запустить сервер выдаёт 
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'kubejs'!
[2024-05-18-2.log.gz](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15358088/2024-05-18-2.log.gz)
[latest.log](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15358095/latest.log)
[startup.log](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15358100/startup.log)
Логи какие нашёл приложил

**Comment by DenisMasterHerobrine** [comment]
Не все моды были загружены на сервер, проблема не в сборке.
