### ISSUE TITLE
Как выбрать класс?

### ISSUE THREAD

**Issue by EndrickN** [DenisMasterHerobrine/ElerionBloodNSteel#85]
Как выбрать класс и какой мод за это отвечает?

**Comment by irunil-ru** [comment]
Чтобы выбрать класс, необходимо прописать следующую команду:
`/skills set [name] <role> <true/false>`
Где [name] - необязательно, имя игрока
<role> - technician (технари), magician и later_content (маги)

Но пока как я понял, в общедоступной сборке они не на что не влияют, по крайней мере, я не заметил

Ну или я что-то неправильно понял, но это единственное что я нашёл для разделения по классам

**Comment by EndrickN** [comment]
А что это за мод?

**Comment by DenisMasterHerobrine** [comment]
Пока никак. В обновлении 0.9.6 или 0.9.7 будет реализовано и доведено до ума. Та команда, которую подсказали - ни на что не влияет, и later_content - контент в разработке и в бете для Boosty нету этого контента, как и выбора для разделения.
