### ISSUE TITLE
Краш

### ISSUE THREAD

**Issue by nofun1** [DenisMasterHerobrine/ElerionBloodNSteel#88]
Спокойно себе ходил и в чате вылезло синим цветом "ruina" что-то. Теперь нельзя зайти в мир, что делать теперь?
[crash-2024-05-19_00.13.11-server.txt](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15366890/crash-2024-05-19_00.13.11-server.txt)

**Comment by irunil-ru** [comment]
У тебя переполнился стэк вызовов, заметил у тебя во флагах запуска некорректность
Во первых:
`-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M` - убери эти флаги, сборка даже при твоём кол-ве памяти хорошо работает

Во вторых:
`-Xss1M -Xmx9000M` - некорректное написание флага `-Xms1M`, лучше всего использовать флаги с `G`, т.е `-Xms1G -Xmx9G`, заместо `M`, это уже устаревшая формулировка и нужна для более детальной настройки по памяти

В третьих: чем тебя не устраивают стандартные флаги которые стоят изначально в сборке?

Также если используешь свой комп для игры с друзьями, почему просто не хочешь открывать мир по локальной сети, учитывая всю нагрузку - это намного лучше скажется на работе сервера, потому что комп может не вывозить

**Comment by nofun1** [comment]
Спасибо за ответ. На счет первых двух пунктов, для меня кодинг это тёмный лес и я понял максимально мало. Мне нужно зайти в какой-то текстовый документ и что-то поменять? Никаких флагов не менял, как распаковал архив со сборкой и скинул её в .minecraft ничего с ней не делал. Кстати на счет сервера. У меня до какого-то момента в краш репортах пишется клиент, а последние 4 подписаны как сервер, почему оно поменялось я не знаю и сильно ли этот момент влияет на количество тпс? Буду благодарен за более подробную помощь, а то я один голову себе сверну

**Comment by irunil-ru** [comment]
@nofun1 
Смотри, всё просто, ты когда скачивал сборка с [Boosty](https://boosty.to/denismasterherobrine), там было прикреплено два файла: один с сервером, другой с клиентом, тот что весит больше клиентский, тот что меньше серверный

В серверном там есть два файла запуска сервера: один под Linux с расширением `.sh`, второй под Windows с расширением `.ps1`

Также серверную часть необязательно кидать в папку `.minecraft`, её можно распаковать в любом другом месте, хоть на рабочем столе, главное создай отдельную папку под него

Также проверь последней ли версии у тебя сборка, она обновилась неделю назад, мб ты не заметил

**Comment by nofun1** [comment]
Так когда у меня вылезла эта смешная ошибка я первым делом полез на бусти и скачал обновлённую клиентскую версию, думал это поможет и я смогу зайти в мир. Не помогло. И вот я тут. Что мне делать-то? Переустановить сборку или как?

**Comment by irunil-ru** [comment]
@nofun1
Тут уже только новый мир, потому что возможно у тебя там появилась сущность которая перегружает всё, либо чешуйницы, которые и крашат тебе мир

**Comment by nofun1** [comment]
А откат не поможет? Неприятно терять весь прогресс. Часто вообще такой прикол может происходить?

**Comment by irunil-ru** [comment]
@nofun1 
Может и поможет, не уверен. У меня ни разу такого не было, потенциально 1 из 100 может быть случаев
Понимаю, что неприятно, но зато новый мир и новые возможности и к тому же можно пересмотреть свой старый прогресс и пойти более быстрым путём

**Comment by tr1kright** [comment]
Neruina же мод, который предотвращает тикающих энтити, там мод должен был кильнутся, почему он не работает?

**Comment by irunil-ru** [comment]
> Neruina же мод, который предотвращает тикающих энтити, там мод должен был кильнутся, почему он не работает?

В нашей версии Neruina нет авто убийства мобов, оно было добавлено в версии 2.0.0 beta, я думаю в v0.9.5 сборки, будет обновлена Neruina, но на всякий добавлю Issue

**Comment by irunil-ru** [comment]
> А откат не поможет? Неприятно терять весь прогресс. Часто вообще такой прикол может происходить?

Можешь попробовать ещё сам обновить [Neruina](https://www.curseforge.com/minecraft/mc-mods/neruina) на сервере, и посмотреть, возможно проблема региться

**Comment by DenisMasterHerobrine** [comment]
В 0.9.5 Neruina был обновлён. Теперь этой проблемы не должно быть.
