### ISSUE TITLE
Что за мод?

### ISSUE THREAD

**Issue by EndrickN** [DenisMasterHerobrine/ElerionBloodNSteel#91]
Что за мод которые если у тебя несколько рядов хп то он их соединяются и они становятся жёлтыми и рядом с хп пишется x2

**Comment by tr1kright** [comment]
Overflowing Bars

**Comment by EndrickN** [comment]
а какой мод делает так чтоб ты от еды получал хп

**Comment by irunil-ru** [comment]
> а какой мод делает так чтоб ты от еды получал хп

[SOL: Valheim](https://modrinth.com/mod/spice-of-life-valheim-edition/version/1.1.1-fabric-mc1.19.2)
