### ISSUE TITLE
[Suggestion] Update Neruina to v2.0.0beta

### ISSUE THREAD

**Issue by IruNil6** [DenisMasterHerobrine/ElerionBloodNSteel#93]
Update the Neruina mod for greater stability of the server and the world, it will also eliminate problems with a large number of mobs, as was already the case in another Issue (#63) with Silverfishs

Also, this mod has become server-only, do not forget to remove it from the client

[Neruina (CurseForge)](https://www.curseforge.com/minecraft/mc-mods/neruina)
[Neruina (Modbrith)](https://modrinth.com/mod/neruina)

**Comment by DenisMasterHerobrine** [comment]
Updated in 0.9.5.1. It is still included on the client for the reason to resolve some singleplayer issues, due to the fact, that the Singleplayer is the same as local server.
