### ISSUE TITLE
Not textures to drawers

### ISSUE THREAD

**Issue by Fferan** [DenisMasterHerobrine/ElerionBloodNSteel#94]
![Screenshot 2024-05-24 001718](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/assets/121789659/978ae5cf-1555-487b-85a7-c2bd6e377e14)

**Comment by DenisMasterHerobrine** [comment]
Баг ресурспака, поставь любой из встроенных ресурспаков для драверсов.
