### ISSUE TITLE
хекс кастинг требует через чур много мыслей 

### ISSUE THREAD

**Issue by Nold0r** [DenisMasterHerobrine/ElerionBloodNSteel#95]
при любам использовании заклинаний из хекс кастинг даже самого банального которое не требует мысли выдаёт
такую фразу: 

Руны потребовали больше мысли чем у меня было…
Возможно следовало дополнительно проверить расчёты.

причём в креативе всё работает

**Comment by DenisMasterHerobrine** [comment]
Это было изначально сделано для баланса на сервере, сейчас такого не должно быть.
