### ISSUE TITLE
Сбой игры

### ISSUE THREAD

**Issue by Fferan** [DenisMasterHerobrine/ElerionBloodNSteel#96]
Периодически происходит сбой игры
В логах перед закрытием пишет, что не получается отрендерить какие-то текстуры мобов и др.
Скидываю 2 последних лога и код ошибки
[logs (2).zip](https://github.com/DenisMasterHerobrine/ElerionBloodNSteel/files/15467265/logs.2.zip)

**Comment by irunil-ru** [comment]
Попробуй переустановить сборку и попробуй поставить последний Fabric на сборку, также скинуть краш-репорт

**Comment by DenisMasterHerobrine** [comment]
Скорее всего нехватило оперативы. Попробуй выделить больше памяти или переставить JDK.
