### ISSUE TITLE
Краш игры (Spectrum)

### ISSUE THREAD

**Issue by FelixArvg** [DenisMasterHerobrine/ElerionBloodNSteel#98]
При ломании цветка игра из мира DD игра крашнулась.
Не получается зайти в мире потому что снова крашит
[crash-2024-05-31_11.31.12-server.txt](https://github.com/user-attachments/files/15507387/crash-2024-05-31_11.31.12-server.txt)

**Comment by DenisMasterHerobrine** [comment]
Исправлено в 0.9.5.1.
